name: flutter_contest
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Firebase
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1

  #UI
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  shimmer: ^2.0.0
  flutter_screenutil: ^5.6.0
  lottie: ^2.2.0

  #Business logic needs
  json_serializable: ^6.3.1
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  permission_handler: ^10.2.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  #File (storage) needs
  path_provider: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  open_file_safe: ^3.2.3

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
